-- Tables are not sorted because: 
-- Circular reference between DEFAULT_SCHEMA.Inmueble and DEFAULT_SCHEMA.Comunidad
-- Try generating Foreign Keys with ALTER TABLE statements.
DROP TABLE DEFAULT_SCHEMA.Carta IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.Concepto IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.LineaFactura IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.ReciboInmueble IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.Propietario IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.DatosBancarios IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.Inmueble IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.NotaInformativa IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.Factura IF EXISTS;
DROP TABLE DEFAULT_SCHEMA.Comunidad IF EXISTS;











