INSERT INTO INMUEBLE (ID_INMUEBLE, ESCALERA, ID_COMUNIDAD, ID_DATOSBANCARIOS, ID_PROPIETARIO, PISO, PORCENTAJE, PUERTA)
VALUES (1,'1',1,1,1,'PISO',1,'PUERTA');

INSERT INTO COMUNIDAD (ID_COMUNIDAD, CALLE, ID_INMUEBLE_PRESIDENTE, MAXRECIBOSPENDIENTES) 
VALUES (1,'CALLE',1,1);

INSERT INTO PROPIETARIO (ID_PROPIETARIO, DIRECCION, FECHAALTA, NIF, NOMBRE, OBSERVACIONES, POBLACION, TELEFONO) 
VALUES (5,'DIRECCION','FECHAALTA','NIF','NOMBRE','OBSERVACIONES','POBLACION','TELEFONO');

