// default package
// Generated Mar 21, 2013 11:01:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * Carta generated by hbm2java
 */
public class Carta implements java.io.Serializable {

	private int id;
	private Reciboinmueble reciboinmueble;
	private String fecha;

	public Carta() {
	}

	public Carta(int id) {
		this.id = id;
	}

	public Carta(int id, Reciboinmueble reciboinmueble, String fecha) {
		this.id = id;
		this.reciboinmueble = reciboinmueble;
		this.fecha = fecha;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Reciboinmueble getReciboinmueble() {
		return this.reciboinmueble;
	}

	public void setReciboinmueble(Reciboinmueble reciboinmueble) {
		this.reciboinmueble = reciboinmueble;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

}
