// default package
// Generated Mar 21, 2013 11:01:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Comunidad generated by hbm2java
 */
public class Comunidad implements java.io.Serializable {

	private int idComunidad;
	private String calle;
	private Integer maxrecibospendientes;
	private String estado;
	private Integer idInmueblePresidente;
	private Set facturas = new HashSet(0);
	private Set inmuebles = new HashSet(0);
	private Set notainformativas = new HashSet(0);

	public Comunidad() {
	}

	public Comunidad(int idComunidad) {
		this.idComunidad = idComunidad;
	}

	public Comunidad(int idComunidad, String calle,
			Integer maxrecibospendientes, String estado,
			Integer idInmueblePresidente, Set facturas, Set inmuebles,
			Set notainformativas) {
		this.idComunidad = idComunidad;
		this.calle = calle;
		this.maxrecibospendientes = maxrecibospendientes;
		this.estado = estado;
		this.idInmueblePresidente = idInmueblePresidente;
		this.facturas = facturas;
		this.inmuebles = inmuebles;
		this.notainformativas = notainformativas;
	}

	public int getIdComunidad() {
		return this.idComunidad;
	}

	public void setIdComunidad(int idComunidad) {
		this.idComunidad = idComunidad;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getMaxrecibospendientes() {
		return this.maxrecibospendientes;
	}

	public void setMaxrecibospendientes(Integer maxrecibospendientes) {
		this.maxrecibospendientes = maxrecibospendientes;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getIdInmueblePresidente() {
		return this.idInmueblePresidente;
	}

	public void setIdInmueblePresidente(Integer idInmueblePresidente) {
		this.idInmueblePresidente = idInmueblePresidente;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

	public Set getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Set getNotainformativas() {
		return this.notainformativas;
	}

	public void setNotainformativas(Set notainformativas) {
		this.notainformativas = notainformativas;
	}

}
