// default package
// Generated Mar 21, 2013 11:01:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	private Integer numfactura;
	private Comunidad comunidad;
	private String fechafactura;
	private Set lineafacturas = new HashSet(0);
	private Set notainformativas = new HashSet(0);

	public Factura() {
	}

	public Factura(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public Factura(Comunidad comunidad, String fechafactura, Set lineafacturas,
			Set notainformativas) {
		this.comunidad = comunidad;
		this.fechafactura = fechafactura;
		this.lineafacturas = lineafacturas;
		this.notainformativas = notainformativas;
	}

	public Integer getNumfactura() {
		return this.numfactura;
	}

	public void setNumfactura(Integer numfactura) {
		this.numfactura = numfactura;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public String getFechafactura() {
		return this.fechafactura;
	}

	public void setFechafactura(String fechafactura) {
		this.fechafactura = fechafactura;
	}

	public Set getLineafacturas() {
		return this.lineafacturas;
	}

	public void setLineafacturas(Set lineafacturas) {
		this.lineafacturas = lineafacturas;
	}

	public Set getNotainformativas() {
		return this.notainformativas;
	}

	public void setNotainformativas(Set notainformativas) {
		this.notainformativas = notainformativas;
	}

}
