package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Carta generated by hbm2java
 */
public class Carta implements java.io.Serializable {

	private int idCarta;
	private String fecha;
	private Set reciboinmuebles = new HashSet(0);

	public Carta() {
	}

	public Carta(int idCarta) {
		this.idCarta = idCarta;
	}

	public Carta(int idCarta, String fecha, Set reciboinmuebles) {
		this.idCarta = idCarta;
		this.fecha = fecha;
		this.reciboinmuebles = reciboinmuebles;
	}

	public int getIdCarta() {
		return this.idCarta;
	}

	public void setIdCarta(int idCarta) {
		this.idCarta = idCarta;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Set getReciboinmuebles() {
		return this.reciboinmuebles;
	}

	public void setReciboinmuebles(Set reciboinmuebles) {
		this.reciboinmuebles = reciboinmuebles;
	}

}
