package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Comunidad generated by hbm2java
 */
public class Comunidad implements java.io.Serializable {

	private int idComunidad;
	private Comunidad comunidad;
	private String calle;
	private Integer maxrecibospendientes;
	private String estado;
	private Integer idInmueblePresidente;
	private Inmueble inmuebles = new Inmueble();
	private Factura facturas = new Factura();
	private Notainformativa notainformativas = new Notainformativa();

	public Comunidad() {
	}

	public Comunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public Comunidad(Comunidad comunidad, String calle,
			Integer maxrecibospendientes, String estado,
			Integer idInmueblePresidente, Inmueble inmuebles, Factura facturas,
			Notainformativa notainformativas) {
		this.comunidad = comunidad;
		this.calle = calle;
		this.maxrecibospendientes = maxrecibospendientes;
		this.estado = estado;
		this.idInmueblePresidente = idInmueblePresidente;
		this.inmuebles = inmuebles;
		this.facturas = facturas;
		this.comunidad = comunidad;
		this.notainformativas = notainformativas;
	}

	public int getIdComunidad() {
		return this.idComunidad;
	}

	public void setIdComunidad(int idComunidad) {
		this.idComunidad = idComunidad;
	}


	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getMaxrecibospendientes() {
		return this.maxrecibospendientes;
	}

	public void setMaxrecibospendientes(Integer maxrecibospendientes) {
		this.maxrecibospendientes = maxrecibospendientes;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getIdInmueblePresidente() {
		return this.idInmueblePresidente;
	}

	public void setIdInmueblePresidente(Integer idInmueblePresidente) {
		this.idInmueblePresidente = idInmueblePresidente;
	}


	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public Inmueble getInmuebles() {
		return inmuebles;
	}

	public void setInmuebles(Inmueble inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Factura getFacturas() {
		return facturas;
	}

	public void setFacturas(Factura facturas) {
		this.facturas = facturas;
	}

	public Notainformativa getNotainformativas() {
		return notainformativas;
	}

	public void setNotainformativas(Notainformativa notainformativas) {
		this.notainformativas = notainformativas;
	}


}
