package negocio;

/**
 * Concepto generated by hbm2java
 */
public class Concepto implements java.io.Serializable {

	private Integer idConcepto;
	private Lineafactura lineafactura;
	private String claveconcepto;
	private String descripcion;

	public Concepto() {
	}

	public Concepto(Lineafactura lineafactura) {
		this.lineafactura = lineafactura;
	}

	public Concepto(Lineafactura lineafactura, String claveconcepto,
			String descripcion) {
		this.lineafactura = lineafactura;
		this.claveconcepto = claveconcepto;
		this.descripcion = descripcion;
	}

	public Integer getIdConcepto() {
		return this.idConcepto;
	}

	public void setIdConcepto(Integer idConcepto) {
		this.idConcepto = idConcepto;
	}

	public Lineafactura getLineafactura() {
		return this.lineafactura;
	}

	public void setLineafactura(Lineafactura lineafactura) {
		this.lineafactura = lineafactura;
	}

	public String getClaveconcepto() {
		return this.claveconcepto;
	}

	public void setClaveconcepto(String claveconcepto) {
		this.claveconcepto = claveconcepto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
