package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto implements java.io.Serializable {

	private Integer idConcepto;
	private String claveconcepto;
	private String descripcion;
	private Set lineafacturas = new HashSet(0);

	public Concepto() {
	}

	public Concepto(String claveconcepto, String descripcion, Set lineafacturas) {
		this.claveconcepto = claveconcepto;
		this.descripcion = descripcion;
		this.lineafacturas = lineafacturas;
	}

	public Integer getIdConcepto() {
		return this.idConcepto;
	}

	public void setIdConcepto(Integer idConcepto) {
		this.idConcepto = idConcepto;
	}

	public String getClaveconcepto() {
		return this.claveconcepto;
	}

	public void setClaveconcepto(String claveconcepto) {
		this.claveconcepto = claveconcepto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getLineafacturas() {
		return this.lineafacturas;
	}

	public void setLineafacturas(Set lineafacturas) {
		this.lineafacturas = lineafacturas;
	}

}
