package negocio;
/**
 * Datosbancarios generated by hbm2java
 */
public class Datosbancarios implements java.io.Serializable {

	private int id;
	private Inmueble inmueble;
	private String entidad;
	private String numerocuenta;

	public Datosbancarios() {
	}

	public Datosbancarios(int id, Inmueble inmueble) {
		this.id = id;
		this.inmueble = inmueble;
	}

	public Datosbancarios(int id, Inmueble inmueble, String entidad,
			String numerocuenta) {
		this.id = id;
		this.inmueble = inmueble;
		this.entidad = entidad;
		this.numerocuenta = numerocuenta;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	public String getNumerocuenta() {
		return this.numerocuenta;
	}

	public void setNumerocuenta(String numerocuenta) {
		this.numerocuenta = numerocuenta;
	}

}
