package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	private Integer numfactura;
	private Notainformativa notainformativa;
	private Comunidad comunidad;
	private String fechafactura;
	private Set lineafacturas = new HashSet(0);

	public Factura() {
	}

	public Factura(Notainformativa notainformativa, Comunidad comunidad,
			String fechafactura, Set lineafacturas) {
		this.notainformativa = notainformativa;
		this.comunidad = comunidad;
		this.fechafactura = fechafactura;
		this.lineafacturas = lineafacturas;
	}

	public Integer getNumfactura() {
		return this.numfactura;
	}

	public void setNumfactura(Integer numfactura) {
		this.numfactura = numfactura;
	}

	public Notainformativa getNotainformativa() {
		return this.notainformativa;
	}

	public void setNotainformativa(Notainformativa notainformativa) {
		this.notainformativa = notainformativa;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public String getFechafactura() {
		return this.fechafactura;
	}

	public void setFechafactura(String fechafactura) {
		this.fechafactura = fechafactura;
	}

	public Set getLineafacturas() {
		return this.lineafacturas;
	}

	public void setLineafacturas(Set lineafacturas) {
		this.lineafacturas = lineafacturas;
	}

}
