package negocio;

import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble implements java.io.Serializable {

	private int idInmueble;
	private Comunidad comunidad;
	private String escalera;
	private String piso;
	private String puerta;
	private Double porcentaje;
	private Set datosbancarioses = new HashSet(0);
	private Set propietarios = new HashSet(0);
	private Set reciboinmuebles = new HashSet(0);

	public Inmueble() {
	}

	public Inmueble(int idInmueble, Comunidad comunidad) {
		this.idInmueble = idInmueble;
		this.comunidad = comunidad;
	}

	public Inmueble(int idInmueble, Comunidad comunidad, String escalera,
			String piso, String puerta, Double porcentaje,
			Set datosbancarioses, Set propietarios, Set reciboinmuebles) {
		this.idInmueble = idInmueble;
		this.comunidad = comunidad;
		this.escalera = escalera;
		this.piso = piso;
		this.puerta = puerta;
		this.porcentaje = porcentaje;
		this.datosbancarioses = datosbancarioses;
		this.propietarios = propietarios;
		this.reciboinmuebles = reciboinmuebles;
	}

	public int getIdInmueble() {
		return this.idInmueble;
	}

	public void setIdInmueble(int idInmueble) {
		this.idInmueble = idInmueble;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public String getEscalera() {
		return this.escalera;
	}

	public void setEscalera(String escalera) {
		this.escalera = escalera;
	}

	public String getPiso() {
		return this.piso;
	}

	public void setPiso(String piso) {
		this.piso = piso;
	}

	public String getPuerta() {
		return this.puerta;
	}

	public void setPuerta(String puerta) {
		this.puerta = puerta;
	}

	public Double getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Set getDatosbancarioses() {
		return this.datosbancarioses;
	}

	public void setDatosbancarioses(Set datosbancarioses) {
		this.datosbancarioses = datosbancarioses;
	}

	public Set getPropietarios() {
		return this.propietarios;
	}

	public void setPropietarios(Set propietarios) {
		this.propietarios = propietarios;
	}

	public Set getReciboinmuebles() {
		return this.reciboinmuebles;
	}

	public void setReciboinmuebles(Set reciboinmuebles) {
		this.reciboinmuebles = reciboinmuebles;
	}

}
