package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

/**
 * Lineafactura generated by hbm2java
 */
public class Lineafactura implements java.io.Serializable {

	private Integer idLineafactura;
	private Factura factura;
	private Concepto concepto;
	private Double importelinea;
	private String observacion;

	public Lineafactura() {
	}

	public Lineafactura(Factura factura, Concepto concepto,
			Double importelinea, String observacion) {
		this.factura = factura;
		this.concepto = concepto;
		this.importelinea = importelinea;
		this.observacion = observacion;
	}

	public Integer getIdLineafactura() {
		return this.idLineafactura;
	}

	public void setIdLineafactura(Integer idLineafactura) {
		this.idLineafactura = idLineafactura;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public Concepto getConcepto() {
		return this.concepto;
	}

	public void setConcepto(Concepto concepto) {
		this.concepto = concepto;
	}

	public Double getImportelinea() {
		return this.importelinea;
	}

	public void setImportelinea(Double importelinea) {
		this.importelinea = importelinea;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
