package negocio;
import java.util.HashSet;
import java.util.Set;

/**
 * Notainformativa generated by hbm2java
 */
public class Notainformativa implements java.io.Serializable {

	private Integer idNotainformativa;
	private Comunidad comunidad;
	private Factura factura;
	private String fechacalculo;
	private Double importenota;
	private Set reciboinmuebles = new HashSet(0);

	public Notainformativa() {
	}

	public Notainformativa(Comunidad comunidad, Factura factura) {
		this.comunidad = comunidad;
		this.factura = factura;
	}

	public Notainformativa(Comunidad comunidad, Factura factura,
			String fechacalculo, Double importenota, Set reciboinmuebles) {
		this.comunidad = comunidad;
		this.factura = factura;
		this.fechacalculo = fechacalculo;
		this.importenota = importenota;
		this.reciboinmuebles = reciboinmuebles;
	}

	public Integer getIdNotainformativa() {
		return this.idNotainformativa;
	}

	public void setIdNotainformativa(Integer idNotainformativa) {
		this.idNotainformativa = idNotainformativa;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public String getFechacalculo() {
		return this.fechacalculo;
	}

	public void setFechacalculo(String fechacalculo) {
		this.fechacalculo = fechacalculo;
	}

	public Double getImportenota() {
		return this.importenota;
	}

	public void setImportenota(Double importenota) {
		this.importenota = importenota;
	}

	public Set getReciboinmuebles() {
		return this.reciboinmuebles;
	}

	public void setReciboinmuebles(Set reciboinmuebles) {
		this.reciboinmuebles = reciboinmuebles;
	}

}
