package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Notainformativa generated by hbm2java
 */
public class Notainformativa implements java.io.Serializable {

	private Integer idNotainformativa;
	private Comunidad comunidad;
	private String fechacalculo;
	private Double importenota;
	private Set facturas = new HashSet(0);
	private Set reciboinmuebles = new HashSet(0);

	public Notainformativa() {
	}

	public Notainformativa(Comunidad comunidad, String fechacalculo,
			Double importenota, Set facturas, Set reciboinmuebles) {
		this.comunidad = comunidad;
		this.fechacalculo = fechacalculo;
		this.importenota = importenota;
		this.facturas = facturas;
		this.reciboinmuebles = reciboinmuebles;
	}

	public Integer getIdNotainformativa() {
		return this.idNotainformativa;
	}

	public void setIdNotainformativa(Integer idNotainformativa) {
		this.idNotainformativa = idNotainformativa;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public String getFechacalculo() {
		return this.fechacalculo;
	}

	public void setFechacalculo(String fechacalculo) {
		this.fechacalculo = fechacalculo;
	}

	public Double getImportenota() {
		return this.importenota;
	}

	public void setImportenota(Double importenota) {
		this.importenota = importenota;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

	public Set getReciboinmuebles() {
		return this.reciboinmuebles;
	}

	public void setReciboinmuebles(Set reciboinmuebles) {
		this.reciboinmuebles = reciboinmuebles;
	}

}
