package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Propietario generated by hbm2java
 */
public class Propietario implements java.io.Serializable {

	private int idPropietario;
	private String nif;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telefono;
	private String observaciones;
	private String fechaalta;
	private Set inmuebles = new HashSet(0);

	public Propietario() {
	}

	public Propietario(int idPropietario) {
		this.idPropietario = idPropietario;
	}

	public Propietario(int idPropietario, String nif, String nombre,
			String direccion, String poblacion, String telefono,
			String observaciones, String fechaalta, Set inmuebles) {
		this.idPropietario = idPropietario;
		this.nif = nif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.observaciones = observaciones;
		this.fechaalta = fechaalta;
		this.inmuebles = inmuebles;
	}

	public int getIdPropietario() {
		return this.idPropietario;
	}

	public void setIdPropietario(int idPropietario) {
		this.idPropietario = idPropietario;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(String fechaalta) {
		this.fechaalta = fechaalta;
	}

	public Set getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set inmuebles) {
		this.inmuebles = inmuebles;
	}

}
