package negocio;

// Generated 21-mar-2013 18:13:29 by Hibernate Tools 3.4.0.CR1

/**
 * Reciboinmueble generated by hbm2java
 */
public class Reciboinmueble implements java.io.Serializable {

	private Integer idReciboinmueble;
	private Notainformativa notainformativa;
	private Inmueble inmueble;
	private Carta carta;
	private String fechapago;
	private Double importe;
	private String pagado;

	public Reciboinmueble() {
	}

	public Reciboinmueble(Notainformativa notainformativa, Inmueble inmueble,
			Carta carta, String fechapago, Double importe) {
		this.notainformativa = notainformativa;
		this.inmueble = inmueble;
		this.carta = carta;
		this.fechapago = fechapago;
		this.importe = importe;
	}

	public Integer getIdReciboinmueble() {
		return this.idReciboinmueble;
	}

	public void setIdReciboinmueble(Integer idReciboinmueble) {
		this.idReciboinmueble = idReciboinmueble;
	}

	public String getPagado() {
		return pagado;
	}

	public void setPagado(String pagado) {
		this.pagado = pagado;
	}

	public Notainformativa getNotainformativa() {
		return this.notainformativa;
	}

	public void setNotainformativa(Notainformativa notainformativa) {
		this.notainformativa = notainformativa;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public Carta getCarta() {
		return this.carta;
	}

	public void setCarta(Carta carta) {
		this.carta = carta;
	}

	public String getFechapago() {
		return this.fechapago;
	}

	public void setFechapago(String fechapago) {
		this.fechapago = fechapago;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

}
