// Generated Mar 21, 2013 11:01:57 AM by Hibernate Tools 3.4.0.CR1
package negocio;
import java.util.HashSet;
import java.util.Set;

/**
 * Reciboinmueble generated by hbm2java
 */
public class Reciboinmueble implements java.io.Serializable {

	private Integer idReciboinmueble;
	private Notainformativa notainformativa;
	private Inmueble inmueble;
	private String fechapago;
	private Double importe;
	private Set cartas = new HashSet(0);

	public Reciboinmueble() {
	}

	public Reciboinmueble(Notainformativa notainformativa, Inmueble inmueble,
			String fechapago, Double importe, Set cartas) {
		this.notainformativa = notainformativa;
		this.inmueble = inmueble;
		this.fechapago = fechapago;
		this.importe = importe;
		this.cartas = cartas;
	}

	public Integer getIdReciboinmueble() {
		return this.idReciboinmueble;
	}

	public void setIdReciboinmueble(Integer idReciboinmueble) {
		this.idReciboinmueble = idReciboinmueble;
	}

	public Notainformativa getNotainformativa() {
		return this.notainformativa;
	}

	public void setNotainformativa(Notainformativa notainformativa) {
		this.notainformativa = notainformativa;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public String getFechapago() {
		return this.fechapago;
	}

	public void setFechapago(String fechapago) {
		this.fechapago = fechapago;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	public Set getCartas() {
		return this.cartas;
	}

	public void setCartas(Set cartas) {
		this.cartas = cartas;
	}

}
